#assignment file meta
#Tue Jun 30 20:17:34 CST 2026
contentType=application/vnd.openxmlformats-officedocument.wordprocessingml.document
fileSize=10725
originalName=\u7FFB\u8BD1.docx
storedName=3e667307-a5c2-45a6-be88-bc79e51969af.docx
