spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/class_assignment
    username: root
    password: zgj0304123Z
mybatis:
  #  ????????
  type-aliases-package: org.example.classAssignment.pojo
  #  ??????
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.classAssignment.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
deepseek:
  api-key: sk-c5e1b95c8567409a858d9aff5cb87d9e
  api-url: https://api.deepseek.com/chat/completions
  model: deepseek-chat