#assignment file meta
#Tue Jun 23 18:47:57 CST 2026
contentType=application/vnd.openxmlformats-officedocument.presentationml.presentation
fileSize=3229166
originalName=\u7B2C8\u7AE0 \u8F6F\u4EF6\u8D28\u91CF\u5C5E\u6027.pptx
storedName=759ffa43-9acf-4cdf-baf1-124fbf6a600a.pptx
