#assignment file meta
#Tue Jun 23 16:43:03 CST 2026
contentType=application/vnd.openxmlformats-officedocument.wordprocessingml.document
fileSize=14294
originalName=\u300A\u8F6F\u4EF6\u5DE5\u7A0B\u4E0E\u8BA1\u7B97II\u300B\u8BC4\u5206\u8868.docx
storedName=f704709e-9f7d-4241-9166-4e14efff614b.docx
