#assignment file meta
#Thu Jun 25 14:40:34 CST 2026
contentType=application/vnd.openxmlformats-officedocument.wordprocessingml.document
fileSize=10725
originalName=\u7FFB\u8BD1.docx
storedName=ec55e188-dddc-4b01-a687-bd0d73364bf4.docx
