#assignment file meta
#Wed Jul 01 16:22:18 CST 2026
contentType=application/vnd.openxmlformats-officedocument.wordprocessingml.document
fileSize=213891
originalName=\u300A\u9AD8\u7EA7Java\u5F00\u53D1\u6280\u672F\u300B\u9879\u76EE5 \u6210\u7EE9\u8BC4\u5B9A\u8868.docx
storedName=a8fcad3e-0ea6-46d8-b715-b1ba1bd27b9f.docx
