#assignment file meta
#Wed Jun 24 19:58:38 CST 2026
contentType=application/vnd.openxmlformats-officedocument.wordprocessingml.document
fileSize=14294
originalName=\u300A\u8F6F\u4EF6\u5DE5\u7A0B\u4E0E\u8BA1\u7B97II\u300B\u8BC4\u5206\u8868.docx
storedName=b2301f8c-d233-4a0c-8c38-ebac263ecda0.docx
