#assignment file meta
#Wed Jun 24 09:10:32 CST 2026
contentType=application/vnd.openxmlformats-officedocument.wordprocessingml.document
fileSize=14294
originalName=\u300A\u8F6F\u4EF6\u5DE5\u7A0B\u4E0E\u8BA1\u7B97II\u300B\u8BC4\u5206\u8868.docx
storedName=d281c5c9-6cfa-4a3c-9670-f19b8fae7285.docx
